version: "3.7"
services:
  rn_expo:
    build: .
    expose:
      - "19000"
      - "19001"
      - "19002"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.120.42
    volumes:
      - .:/home
